/*
 * Copyright (C) 2016-2017 Socionext Inc.
 *   Author: Masahiro Yamada <yamada.masahiro@socionext.com>
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */

#include "clk-uniphier.h"

#define UNIPHIER_PERI_CLK_UART(id, ch)					\
	UNIPHIER_CLK_GATE(id, 128, 0x24, 19 + (ch))

#define UNIPHIER_PERI_CLK_I2C(id, ch)					\
	UNIPHIER_CLK_GATE(id, 129, 0x24, 5 + (ch))

#define UNIPHIER_PERI_CLK_FI2C(id, ch)					\
	UNIPHIER_CLK_GATE(id, 129, 0x24, 24 + (ch))

const struct uniphier_clk_data uniphier_ld4_peri_clk_data[] = {
#ifdef CONFIG_ARCH_UNIPHIER_LD4
	UNIPHIER_CLK_RATE(128, 36864000),
	UNIPHIER_CLK_RATE(129, 99840000),
	UNIPHIER_PERI_CLK_UART(0, 0),
	UNIPHIER_PERI_CLK_UART(1, 1),
	UNIPHIER_PERI_CLK_UART(2, 2),
	UNIPHIER_PERI_CLK_UART(3, 3),
	UNIPHIER_PERI_CLK_I2C(4, 0),
	UNIPHIER_PERI_CLK_I2C(5, 1),
	UNIPHIER_PERI_CLK_I2C(6, 2),
	UNIPHIER_PERI_CLK_I2C(7, 3),
	UNIPHIER_PERI_CLK_I2C(8, 4),
	UNIPHIER_PERI_CLK_I2C(9, 5),
	UNIPHIER_PERI_CLK_I2C(10, 6),
	{ /* sentinel */ }
#endif
};

const struct uniphier_clk_data uniphier_sld8_peri_clk_data[] = {
#ifdef CONFIG_ARCH_UNIPHIER_SLD8
	UNIPHIER_CLK_RATE(128, 80000000),
	UNIPHIER_CLK_RATE(129, 100000000),
	UNIPHIER_PERI_CLK_UART(0, 0),
	UNIPHIER_PERI_CLK_UART(1, 1),
	UNIPHIER_PERI_CLK_UART(2, 2),
	UNIPHIER_PERI_CLK_UART(3, 3),
	UNIPHIER_PERI_CLK_I2C(4, 0),
	UNIPHIER_PERI_CLK_I2C(5, 1),
	UNIPHIER_PERI_CLK_I2C(6, 2),
	UNIPHIER_PERI_CLK_I2C(7, 3),
	UNIPHIER_PERI_CLK_I2C(8, 4),
	UNIPHIER_PERI_CLK_I2C(9, 5),
	UNIPHIER_PERI_CLK_I2C(10, 6),
	{ /* sentinel */ }
#endif
};

const struct uniphier_clk_data uniphier_pro4_peri_clk_data[] = {
#if defined(CONFIG_ARCH_UNIPHIER_PRO4) || defined(CONFIG_ARCH_UNIPHIER_PRO5)
	UNIPHIER_CLK_RATE(128, 73728000),
	UNIPHIER_CLK_RATE(129, 50000000),
	UNIPHIER_PERI_CLK_UART(0, 0),
	UNIPHIER_PERI_CLK_UART(1, 1),
	UNIPHIER_PERI_CLK_UART(2, 2),
	UNIPHIER_PERI_CLK_UART(3, 3),
	UNIPHIER_PERI_CLK_FI2C(4, 0),
	UNIPHIER_PERI_CLK_FI2C(5, 1),
	UNIPHIER_PERI_CLK_FI2C(6, 2),
	UNIPHIER_PERI_CLK_FI2C(7, 3),
	UNIPHIER_PERI_CLK_FI2C(8, 4),
	UNIPHIER_PERI_CLK_FI2C(9, 5),
	UNIPHIER_PERI_CLK_FI2C(10, 6),
	{ /* sentinel */ }
#endif
};

const struct uniphier_clk_data uniphier_pxs2_peri_clk_data[] = {
#if defined(CONFIG_ARCH_UNIPHIER_PXS2) || defined(CONFIG_ARCH_UNIPHIER_LD6B)
	UNIPHIER_CLK_RATE(128, 88888889),
	UNIPHIER_CLK_RATE(129, 50000000),
	UNIPHIER_PERI_CLK_UART(0, 0),
	UNIPHIER_PERI_CLK_UART(1, 1),
	UNIPHIER_PERI_CLK_UART(2, 2),
	UNIPHIER_PERI_CLK_UART(3, 3),
	UNIPHIER_PERI_CLK_FI2C(4, 0),
	UNIPHIER_PERI_CLK_FI2C(5, 1),
	UNIPHIER_PERI_CLK_FI2C(6, 2),
	UNIPHIER_PERI_CLK_FI2C(7, 3),
	UNIPHIER_PERI_CLK_FI2C(8, 4),
	UNIPHIER_PERI_CLK_FI2C(9, 5),
	UNIPHIER_PERI_CLK_FI2C(10, 6),
	{ /* sentinel */ }
#endif
};

const struct uniphier_clk_data uniphier_ld11_peri_clk_data[] = {
#if defined(CONFIG_ARCH_UNIPHIER_LD11) || defined(CONFIG_ARCH_UNIPHIER_LD20) ||\
    defined(CONFIG_ARCH_UNIPHIER_PXS3)
	UNIPHIER_CLK_RATE(128, 58823529),
	UNIPHIER_CLK_RATE(129, 50000000),
	UNIPHIER_PERI_CLK_UART(0, 0),
	UNIPHIER_PERI_CLK_UART(1, 1),
	UNIPHIER_PERI_CLK_UART(2, 2),
	UNIPHIER_PERI_CLK_UART(3, 3),
	UNIPHIER_PERI_CLK_FI2C(4, 0),
	UNIPHIER_PERI_CLK_FI2C(5, 1),
	UNIPHIER_PERI_CLK_FI2C(6, 2),
	UNIPHIER_PERI_CLK_FI2C(7, 3),
	UNIPHIER_PERI_CLK_FI2C(8, 4),
	UNIPHIER_PERI_CLK_FI2C(9, 5),
	UNIPHIER_PERI_CLK_FI2C(10, 6),
	{ /* sentinel */ }
#endif
};
